myfirstweb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/profil/'), name='redirect-view'),
    path('profil/', include('profil.urls')),
    path('portofolio/', include('portofolio.urls')),
    path('register/', include('register.urls')),#, namespace='register'),
    path('admin/', admin.site.urls),
]

portofolio/urls.py
from django.urls import path

from .views import index

urlpatterns = [
    path('', index, name='portofolio'),
]

profil/urls.py
from django.urls import path

from .views import index

urlpatterns = [
    path('', index, name='profil'),
]

register/urls.py
from django.urls import path

from .views import index, tambah_kegiatan, jadwal_kegiatan, hapus_kegiatan

app_name = 'register'

urlpatterns = [
    path('', index, name='register'),
    path('tambah_kegiatan/', tambah_kegiatan, name='tambah_kegiatan'),
    path('jadwal_kegiatan/', jadwal_kegiatan, name='jadwal_kegiatan'),
    path('hapus_kegiatan/', hapus_kegiatan, name='hapus_kegiatan'),
]

portofolio/models.py
from django.db import models

# Create your models here.

profil/models.py
from django.db import models

# Create your models here.

register/models.py
from datetime import datetime
from django.db import models

# Create your models here.
class JadwalKegiatan(models.Model):
    jadwal = models.DateTimeField(default=datetime.now)
    kegiatan = models.CharField(max_length=50)
    tempat = models.CharField(max_length=50)
    kategori = models.CharField(max_length=50)

register/forms.py
from django import forms

class JadwalForm(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    attrs = {
        'class': 'form-control'
    }

    kegiatan = forms.CharField(label='Kegiatan', required=True, max_length=50, empty_value='Nama Kegiatan', widget=forms.TextInput(attrs=attrs))
    tempat = forms.CharField(label='Tempat', required=True, max_length=50, empty_value='Tempat', widget=forms.TextInput(attrs=attrs))
    jadwal = forms.DateTimeField(label='Jadwal', widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}), required=True, input_formats=['%Y-%m-%dT%H:%M'])
    kategori = forms.CharField(label='Kategori', required=True, max_length=50, empty_value='Kategori', widget=forms.TextInput(attrs=attrs))

portofolio/views.py
from django.shortcuts import render

# Create your views here.
def index(request) :
    response = {}
    return render(request, 'portofolio.html', response)

profil/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    response = {}
    return render(request, 'home.html', response)

register/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .forms import JadwalForm
from .models import JadwalKegiatan

# Create your views here.
def index(request):
    response = {'jadwal_form': JadwalForm}
    return render(request, 'register.html', response)

def tambah_kegiatan(request):
    form = JadwalForm(request.POST or None)
    response = {}
    if(request.method == 'POST' and form.is_valid()):
        response['kegiatan'] = request.POST['kegiatan']
        response['tempat'] = request.POST['tempat']
        response['jadwal'] = request.POST['jadwal']
        response['kategori'] = request.POST['kategori']
        jadwalkegiatan = JadwalKegiatan(kegiatan=response['kegiatan'], tempat=response['tempat'], jadwal=response['jadwal'], kategori=response['kategori'])
        jadwalkegiatan.save()
        return HttpResponseRedirect('/register/jadwal_kegiatan/')
    else:
        return HttpResponseRedirect('/register/')

def jadwal_kegiatan(request):
    response = {}
    daftar_kegiatan = JadwalKegiatan.objects.all()
    response['daftar_kegiatan'] = daftar_kegiatan
    return render(request, 'jadwal_kegiatan.html', response)

def hapus_kegiatan(request):
    JadwalKegiatan.objects.all().delete()
    return HttpResponseRedirect('/register/jadwal_kegiatan/')

myfirstweb/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Selamat datang!{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'profil/style.css' %}">
</head>

<body>
    <div class="logo">
        <img src="{% static 'profil/logo.png' %}" alt="home" href="#tentang" width="75%" height="75%">
    </div>
    <br><br><br>
    <nav class="navbar">
        <div class="topnav">
            <div class="topnav-right">
                {% with request.resolver_match.url_name as url_name %}
                <a class="{% if url_name == 'profil' %}active{% endif %}" href="/profil">Tentang</a>
                <a class="{% if url_name == 'portofolio' %}active{% endif %}" href="/portofolio">Portofolio</a>
                <a class="{% if url_name == 'register' %}active{% endif %}" href="/register">Tambah Jadwal</a>
                <a class="{% if url_name == 'jadwal_kegiatan' %}active{% endif %}" href="/register/jadwal_kegiatan">Jadwal Kegiatan</a>
                {% endwith %}
            </div>
        </div>
    </nav>

    {%block content %}{% endblock %}
    
</body>
</html>

portofolio/templates/portofolio.html
{% extends "base.html" %}

{% block title %}Portofolio{% endblock %}

{% block content %}
<br><br>
<div class="row">
    <div class="column">
        <h2>Bahasa Pemrograman</h2>
        <div class="portofolio">
            <p> - Python<br><br>
                - C / C++<br><br>
                - Java<br><br>
                - HTML</p>
        </div>
    </div>
    <div class="column">
        <h2>Riwayat Pendidikan</h2>
        <div class="portofolio">
            <p> - SDN 03 Tanjung Barat<br><br>
                - SMPN 20 Jakarta<br><br>
                - SMAN 67 Jakarta<br><br>
                - Universitas Indonesia</p>
        </div>
    </div>
    <div class="column">
        <h2>Aktivitas</h2>
        <div class="portofolio">
            <p> - Penanggun jawab Ayo Berinfaq ,Sospol Fuki<br><br>
                - Junior Member Competitive programming, Ristek Fasilkom UI<br><br>
                - Asisten dosen Matematika Dasar 1</p>
        </div>
    </div>
</div>
{% endblock %}

profil/templates/home.html
{% extends "base.html" %}

{% block title %}Selamat datang!{% endblock %}

{% block content %}
<div class="tentang">
    <div class="split left">
        <h2>HALO, SAYA ADLI</h2>
        <div class="box">
            <p>Saya seorang Mahasiswa Fakultas Ilmu Komputer dari Universitas Indonesia. Saya
                Merupakan programmer web junior.
                <br><br>
                Ini merupakan website pertama saya. Enjoy it:)</p>
        </div>
    </div>
    <div class="split right">
        {% load static %}
        <img class="profil" src="{% static 'profil/image.jpg' %}" alt="adli daffa">
        <h2>INFO</h2>
        <div class="info">
            <p><b>Mohammad Adli Daffa</b><br><br>
                - Umur: 19 Tahun<br>
                - Berkuliah di: Universitas Indonesia<br>
                - Hobi: Koding</p>
        </div>
    </div>
</div>
{% endblock %}

register/templates/jadwal_kegiatan.html
{% extends "base.html" %}
    
{% block title %}Jadwal Kegiatan{% endblock %}

{% block content %}
<br><br><br>
<table class="table">
    <thead class="table_header">
        <th>Nama Kegiatan</th>
        <th>Tempat</th>
        <th>Jadwal</th>
        <th>Kategori</th>
    </thead>
    <tbody>
        {% for kegiatan in daftar_kegiatan %}
        <tr>
            <td> {{kegiatan.kegiatan}} </td>
            <td> {{kegiatan.tempat}} </td>
            <td> {{kegiatan.jadwal|date:"l"}}, {{kegiatan.jadwal}} </td>
            <td> {{kegiatan.kategori}} </td>
        </tr>             
        {% endfor %}
    </tbody>
</table>

<br>
<div class="center_button">
    <a class="submit delete_all" href="/register/hapus_kegiatan">Hapus Semua</a>
</div>

{% endblock %}

register/templates/register.html
{% extends "base.html" %}

{% block title %}Tambah Jadwal{% endblock %}

{% block content %}
<br><br><br>
<div class="formulir">
    <h3>Tambah Jadwal</h3>

    <div class="container">
        <form id="form" method="POST" action="{% url 'register:tambah_kegiatan' %}">
            {% csrf_token %}
            {{ jadwal_form }}
            <br>
            <button type="submit" class="submit">Tambah</button>
        </form>
    </div>
</div>
{% endblock %}